// Generates src/data/dexinfo.ts (height/weight of generation 1) from data-src/pokemon-species.csv
// (one row per species, default forms only). Usage: node scripts/gen-dexinfo.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

function parseCsv(text) {
  const rows = [];
  let row = [];
  let cur = '';
  let quoted = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (quoted) {
      if (c === '"') {
        if (text[i + 1] === '"') { cur += '"'; i++; } else quoted = false;
      } else cur += c;
    } else if (c === '"') quoted = true;
    else if (c === ',') { row.push(cur); cur = ''; }
    else if (c === '\n') { row.push(cur.replace(/\r$/, '')); rows.push(row); row = []; cur = ''; }
    else cur += c;
  }
  if (cur || row.length) { row.push(cur); rows.push(row); }
  const [head, ...rest] = rows;
  return rest.filter((r) => r.length === head.length).map((r) => Object.fromEntries(head.map((k, i) => [k, r[i]])));
}

const rows = parseCsv(readFileSync(join(root, 'data-src/pokemon-species.csv'), 'utf8').replace(/^\uFEFF/, ''))
  .filter((r) => Number(r.generation_id) === 1)
  .sort((a, b) => Number(a.id) - Number(b.id));

const lines = rows.map((r) => {
  const h = r.height === '' ? 'null' : Number(r.height);
  const w = r.weight === '' ? 'null' : Number(r.weight);
  return `  ${Number(r.id)}: { height: ${h}, weight: ${w} },`;
});

const out = `// Generated by scripts/gen-dexinfo.mjs from data-src/pokemon-species.csv. Do not edit by hand.
export const DEX_INFO: Record<number, { height: number | null; weight: number | null }> = {
${lines.join('\n')}
};
`;
writeFileSync(join(root, 'src/data/dexinfo.ts'), out);
console.log(`dexinfo.ts: ${rows.length} entries`);
